#!/usr/bin/env python3
"""
Demonstration of API queries generated by the system.

This script shows the actual API queries that would be sent to Freshdesk
and OpenAI without making real API calls.
"""

import sys
from pathlib import Path

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from src.input_handler import FeedbackAnalysisInput
from src.context_loader import GameFeatureContext
from src.ai_classifier import build_classification_prompt


def print_section(title: str):
    """Print a formatted section header."""
    print("\n" + "="*80)
    print(f"  {title}")
    print("="*80 + "\n")


def demo_freshdesk_api_queries():
    """Demonstrate Freshdesk API queries."""
    print_section("FRESHDESK API QUERIES")
    
    # Sample input parameters
    params = FeedbackAnalysisInput(
        game_name="Candy Crush Saga",
        os="Android",
        start_date="2024-01-01",
        end_date="2024-01-31"
    )
    
    print("📋 Sample Input Parameters:")
    print(f"   Game: {params.game_name}")
    print(f"   OS: {params.os}")
    print(f"   Date Range: {params.start_date} to {params.end_date}")
    
    # Construct what the API query would look like
    print("\n🔌 Freshdesk API Request Details:")
    print("-" * 80)
    
    # API endpoint
    domain = "yourcompany.freshdesk.com"  # Replace with your actual domain
    endpoint = f"https://{domain}/api/v2/tickets"
    
    print(f"Endpoint: {endpoint}")
    print(f"Method: GET")
    print(f"Authentication: HTTP Basic Auth (API Key + 'X')")
    
    print("\nQuery Parameters (per page):")
    query_params = {
        'per_page': 100,
        'page': 1,
        'order_by': 'created_at',
        'order_type': 'desc'
    }
    
    for key, value in query_params.items():
        print(f"   {key}: {value}")
    
    print("\nHeaders:")
    print("   Content-Type: application/json")
    print("   Authorization: Basic <base64(api_key:X)>")
    
    print("\n📝 Note: The system fetches broadly from Freshdesk API, then applies")
    print("   STRICT client-side filtering for:")
    print("   • Type = Feedback")
    print("   • Status = Closed (4 or 5)")
    print(f"   • Created date between {params.start_date} and {params.end_date}")
    print(f"   • Game name contains: '{params.game_name}'")
    print(f"   • OS matches: '{params.os}'")
    
    print("\n📊 Pagination:")
    print("   • Page 1: /api/v2/tickets?per_page=100&page=1&order_by=created_at")
    print("   • Page 2: /api/v2/tickets?per_page=100&page=2&order_by=created_at")
    print("   • ... continues until no more results or max_pages reached")
    print("   • Small delay (0.5s) between requests")
    
    print("\n✅ Response Format:")
    print("   JSON array of ticket objects")
    print("   Each ticket contains: id, subject, description, status, created_at, etc.")


def demo_openai_api_query():
    """Demonstrate OpenAI API query with full prompt."""
    print_section("OPENAI API QUERY")
    
    # Sample cleaned ticket
    sample_ticket = {
        'ticket_id': 12345,
        'subject': 'Game crashes on level 50',
        'clean_feedback': 'The game keeps crashing when I reach level 50. This is very frustrating! I have tried reinstalling but the issue persists.',
        'created_date': '2024-01-15T10:30:00Z'
    }
    
    # Sample game context
    sample_context = GameFeatureContext(
        game_name="Candy Crush Saga",
        current_features=[
            "Match-3 puzzle gameplay with various candy types",
            "500+ levels with increasing difficulty",
            "Daily challenges and special events",
            "Boosters and power-ups"
        ],
        known_constraints=[
            "Performance issues on older Android devices (pre-2018)",
            "Level difficulty cannot be changed post-release"
        ],
        recent_changes=[
            "v2.5.0 (Jan 2024): Added new 'Ice Breaker' event",
            "v2.4.8 (Dec 2023): Fixed crash issue on iOS 17 devices"
        ]
    )
    
    print("📋 Sample Clean Ticket:")
    print(f"   ID: #{sample_ticket['ticket_id']}")
    print(f"   Subject: {sample_ticket['subject']}")
    print(f"   Feedback: {sample_ticket['clean_feedback']}")
    
    print("\n🔌 OpenAI API Request Details:")
    print("-" * 80)
    
    print("Endpoint: https://api.openai.com/v1/chat/completions")
    print("Method: POST")
    print("Authentication: Bearer <OPENAI_API_KEY>")
    
    print("\nRequest Body:")
    print("   model: gpt-4-turbo-preview")
    print("   temperature: 0")
    print("   response_format: { type: 'json_object' }")
    
    print("\n📝 Complete Prompt (what AI receives):")
    print("-" * 80)
    
    # Build the actual prompt
    prompt = build_classification_prompt(
        sample_ticket['clean_feedback'],
        sample_ticket['subject'],
        sample_context
    )
    
    print(prompt)
    print("-" * 80)
    
    print("\n✅ Expected Response Format (STRICT JSON):")
    print("-" * 80)
    
    sample_response = {
        "ticket_id": 12345,
        "category": "Bug",
        "subcategory": "Crash/Freeze",
        "sentiment": "Negative",
        "intent": "Report Bug",
        "confidence": 0.95,
        "key_points": [
            "Game crashes consistently on level 50",
            "User tried reinstalling without success",
            "Causing player frustration"
        ],
        "short_summary": "Player reports persistent crash on level 50 despite reinstallation",
        "is_expected_behavior": False,
        "related_feature": "Level progression system"
    }
    
    import json
    print(json.dumps(sample_response, indent=2))
    print("-" * 80)


def demo_complete_workflow():
    """Show complete API workflow."""
    print_section("COMPLETE API WORKFLOW")
    
    print("📊 For a typical analysis run, here's the API call sequence:\n")
    
    workflow_steps = [
        {
            'step': 1,
            'action': 'User provides inputs',
            'apis': 'None (local interaction)',
            'example': 'Game: Candy Crush, OS: Android, Dates: 2024-01-01 to 2024-01-31'
        },
        {
            'step': 2,
            'action': 'Check cache',
            'apis': 'None (local file check)',
            'example': 'Check if data/raw/Feedback_Candy_Crush_Android_2024-01-01_to_2024-01-31.json exists'
        },
        {
            'step': 3,
            'action': 'Fetch from Freshdesk (ONLY if cache miss)',
            'apis': 'Freshdesk API',
            'example': 'GET https://yourcompany.freshdesk.com/api/v2/tickets?per_page=100&page=1'
        },
        {
            'step': 4,
            'action': 'Clean feedback data',
            'apis': 'None (local text processing)',
            'example': 'Remove HTML, signatures, auto-replies from 150 tickets'
        },
        {
            'step': 5,
            'action': 'Load game context',
            'apis': 'None (local YAML file)',
            'example': 'Load context/game_features.yaml'
        },
        {
            'step': 6,
            'action': 'AI Classification (with user confirmation)',
            'apis': 'OpenAI API',
            'example': 'POST https://api.openai.com/v1/chat/completions (150 calls, one per ticket)'
        },
        {
            'step': 7,
            'action': 'Aggregate insights',
            'apis': 'None (local data analysis)',
            'example': 'Group by category, detect patterns, analyze trends'
        },
        {
            'step': 8,
            'action': 'Generate reports',
            'apis': 'None (local file generation)',
            'example': 'Save Markdown and JSON reports'
        }
    ]
    
    for step_info in workflow_steps:
        print(f"Step {step_info['step']}: {step_info['action']}")
        print(f"   APIs Called: {step_info['apis']}")
        print(f"   Example: {step_info['example']}")
        print()
    
    print("💰 API Costs (for 150 tickets):")
    print("   Freshdesk: FREE (included in your subscription)")
    print("   OpenAI: ~$1.50 (150 tickets × $0.01)")
    print("   Total: ~$1.50")
    
    print("\n⏱️  Time Estimate:")
    print("   Cache Hit: 2-5 minutes (no Freshdesk call)")
    print("   Cache Miss: 5-10 minutes (includes Freshdesk fetch)")


def demo_api_call_counts():
    """Show API call counts for different scenarios."""
    print_section("API CALL COUNT ANALYSIS")
    
    scenarios = [
        {
            'name': 'First Run (Cache Miss) - 150 tickets',
            'freshdesk_calls': '~2 calls (1 connection test + 1-2 pages)',
            'openai_calls': '150 calls (1 per ticket)',
            'total_calls': '~152',
            'cost': '~$1.50 (OpenAI only)'
        },
        {
            'name': 'Second Run (Cache Hit) - 150 tickets',
            'freshdesk_calls': '0 calls (using cache!)',
            'openai_calls': '150 calls (1 per ticket)',
            'total_calls': '150',
            'cost': '~$1.50 (OpenAI only)'
        },
        {
            'name': 'Large Dataset (1000 tickets)',
            'freshdesk_calls': '~11 calls (1 test + 10 pages)',
            'openai_calls': '1000 calls (1 per ticket)',
            'total_calls': '~1011',
            'cost': '~$10.00 (OpenAI only)'
        }
    ]
    
    for scenario in scenarios:
        print(f"📊 Scenario: {scenario['name']}")
        print(f"   Freshdesk API: {scenario['freshdesk_calls']}")
        print(f"   OpenAI API: {scenario['openai_calls']}")
        print(f"   Total API Calls: {scenario['total_calls']}")
        print(f"   Estimated Cost: {scenario['cost']}")
        print()


if __name__ == "__main__":
    print("\n" + "🔍 "*40)
    print("  API QUERY DEMONSTRATION")
    print("  (No actual API calls made - just showing the queries)")
    print("🔍 "*40)
    
    demo_freshdesk_api_queries()
    demo_openai_api_query()
    demo_complete_workflow()
    demo_api_call_counts()
    
    print("\n" + "="*80)
    print("✅ DEMONSTRATION COMPLETE")
    print("="*80)
    print("\nThis demonstration showed you the API queries WITHOUT making actual calls.")
    print("When you run 'python main.py', these will be real API calls.")
    print("\n💡 Key Points:")
    print("   • Freshdesk: Called ONLY on cache miss")
    print("   • OpenAI: Called after user confirmation (cost shown)")
    print("   • All queries logged for debugging")
    print("   • Retry logic handles failures automatically")
    print("="*80 + "\n")
